---
sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

cache: false

env:
  - EMBER_TRY_SCENARIO=default

matrix:
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6ba4caae2993b5f2945f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

dist: trusty

addons:
  chrome: stable

before_install:
  - docker --version
  - docker pull flexberry/ember-flexberry-stand-backend:latest
  - docker pull flexberry/ember-flexberry-stand-postgres:latest
  - curl -O https://raw.githubusercontent.com/Flexberry/FlexberryEmberTestStand.ODataBackend/master/Docker/ember-flexberry-stand-postgres.yml
  - docker swarm init
  - docker stack deploy -c ember-flexberry-stand-postgres.yml EmberFlexberryStand

  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - yarn global add ember-cli@2.4.3
  - yarn global add bower
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

install:
  - yarn install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
  - bash ./scripts/test-generator.sh

after_success:
  - test $EMBER_TRY_SCENARIO == "default"
    && test $TRAVIS_PULL_REQUEST == "false"
    && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_BRANCH == "develop" || test $TRAVIS_BRANCH == "feature-ember-update")
    && ember build --gh-pages --gh-pages-branch=$TRAVIS_BRANCH
    && bash scripts/deploy-to-gh-pages.sh

after_script:
  - test $EMBER_TRY_SCENARIO == "default"
    && test $TRAVIS_PULL_REQUEST == "false"
    && (test $TRAVIS_BRANCH == "dummy-test" || test $TRAVIS_BRANCH == "dummy-test-2" || test $TRAVIS_BRANCH == "dummy-test-3")
    && ember build --gh-pages --gh-pages-branch=$TRAVIS_BRANCH
    && bash scripts/deploy-to-gh-pages.sh no-doc
  - test $TRAVIS_PULL_REQUEST != "false"
    && ember build --gh-pages --gh-pages-branch=pull/$TRAVIS_PULL_REQUEST
    && bash scripts/deploy-to-gh-pages.sh no-doc
